{% set version = "6.0" %}

package:
  name: galois
  version: {{ version }}

source:
  path: ../

build:
  number: 3

requirements:
  build:
    - {{ compiler('cxx') }}    
    - {{ cdt('numactl-devel') }}
    - cmake>=3.13
    - make
  host:
    - boost-cpp>=1.71
    - arrow-cpp>=0.17.1,<2.0.0
    - aws-sdk-cpp>=1.7.164
    - eigen>=3.3.7
    - fmt>=6.2.1,<7
    - zlib>=1.2.11
    - ncurses>=6.1
    - llvm>=8
    - {{ cdt('numactl-devel') }}
    - libxml2>=2.9.10
    - libcypher-parser>=0.6.2
    - nlohmann_json>=3.7.3
    - howardhinnant_date>=3.0.0
  run:
    # TODO: use pinning expressions to handle version matching
    #  (https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#pinning-expressions)
    - boost-cpp>=1.71
    - arrow-cpp>=0.17.1,<2.0.0
    - aws-sdk-cpp>=1.7.164
    - eigen>=3.3.7
    - fmt>=6.2.1,<7
    - zlib>=1.2.11
    - ncurses>=6.1
    - libxml2>=2.9.10
    - libcypher-parser>=0.6.2
    - nlohmann_json>=3.7.3
    - howardhinnant_date>=3.0.0

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ cdt('numactl') }}
    - cmake>=3.13
    - make
  files:
    - test_app/CMakeLists.txt
    - test_app/test_app.cpp
  commands:
    - graph-convert --help
      
about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - katanagraph
    - amp
    - insertinterestingnamehere
