{% set version = "6.0" %}

package:
  name: galois-python
  version: {{ version }}

source:
  path: ../../
  patches:

build:
  number: 3
  script_env:
    - GALOIS_DOCS_OUTPUT

requirements:
  build:
    - python
    - scikit-build
    - jinja2
    - {{ compiler('cxx') }}
    - galois={{ version }}
    - cython>=0.29.12
    - numba
    - pyarrow>=0.17.1,<2.0.0
    - sphinx
  host:
    - python
    - scikit-build
    - jinja2
    - {{ compiler('cxx') }}
    - galois={{ version }}
    - cython>=0.29.12
    - numba
    - pyarrow>=0.17.1,<2.0.0
  run:
    - python
    - galois={{ version }}
    # Cython is a runtime dependency because a major use case for the package
    # is to use cython in Jupyter notebooks
    - cython>=0.29.12
    - cxx-compiler
    - numba
    - pyarrow>=0.17.1,<2.0.0

test:
  imports:
    - galois
    - galois.shmem
    - galois.bfs
    - galois.loops
    - galois.graphs
    - galois.property_graph
  requires:
    - jupyter
    - pytest
    - numpy
  files:
    - test_notebook.ipynb
    - torus5.gr
  source_files:
    - tests
  

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - katanagraph
    - amp
    - insertinterestingnamehere
