{% set version = "6.0" %}

package:
  name: galois-python
  version: {{ version }}

source:
  path: ../../
  patches:

build:
  number: 0

requirements:
  build:
    - python
    - scikit-build
    - jinja2
    - cython>=0.29.12
    - {{ compiler('cxx') }}
  host:
    - python
    - scikit-build
    - jinja2
    - {{ compiler('cxx') }}
    - galois={{ version }}
    - cython>=0.29.12
  run:
    - python
    - galois={{ version }}
    # Cython is a runtime dependency because a major use case for the package
    # is to use cython in Jupyter notebooks
    - cython>=0.29.12
    - cxx-compiler

test:
  imports:
    - galois
    - galois.shmem
    - galois.bfs
  requires:
    - jupyter
  files:
    - test_notebook.ipynb
    - torus5.gr
  

about:
  home: https://katanagraph.com/
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - katanagraph
    - amp
    - insertinterestingnamehere
